const {
  ethers: { keccak256, toUtf8Bytes }
} = require('hardhat')

const getRole = (_message) => keccak256(toUtf8Bytes(_message))

module.exports = {
  BORROW_ROLE: getRole('BORROW_ROLE'),
  BURN_ROLE: getRole('BURN_ROLE'),
  CHANGE_MAX_TOTAL_SUPPLY_ROLE: getRole('CHANGE_MAX_TOTAL_SUPPLY_ROLE'),
  CHANGE_TOKEN_ROLE: getRole('CHANGE_TOKEN_ROLE'),
  CREATE_PAYMENTS_ROLE: getRole('CREATE_PAYMENTS_ROLE'),
  CREATE_VOTES_ROLE: getRole('CREATE_VOTES_ROLE'),
  INCREASE_AMOUNT_ROLE: getRole('INCREASE_AMOUNT_ROLE'),
  INCREASE_DURATION_ROLE: getRole('INCREASE_DURATION_ROLE'),
  MINT_ROLE: getRole('MINT_ROLE'),
  REDIRECT_CLAIM_TO_CHALLENGER_BY_EPOCH_ROLE: getRole('REDIRECT_CLAIM_TO_CHALLENGER_BY_EPOCH_ROLE'),
  RELEASE_ROLE: getRole('RELEASE_ROLE'),
  SET_FEES_MANAGER_ROLE: getRole('SET_FEES_MANAGER_ROLE'),
  SET_FORWARDER_ROLE: getRole('SET_FORWARDER_ROLE'),
  SET_GOVERNANCE_MESSAGE_EMITTER_ROLE: getRole('SET_GOVERNANCE_MESSAGE_EMITTER_ROLE'),
  SLASH_ROLE: getRole('SLASH_ROLE'),
  STAKE_ROLE: getRole('STAKE_ROLE'),
  TRANSFER_ROLE: getRole('TRANSFER_ROLE'),
  UPDATE_GUARDIAN_REGISTRATION_ROLE: getRole('UPDATE_GUARDIAN_REGISTRATION_ROLE'),
  UPGRADE_ROLE: getRole('UPGRADE_ROLE'),
  DEPOSIT_REWARD_ROLE: getRole('DEPOSIT_REWARD_ROLE')
}
